import ReactBricksApp from "@/app/admin/ReactBricksApp";

export const metadata = {
  title: "React Bricks Admin",
  description: "Generated by Next.js",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark:bg-gray-900`}>
        <main>
          <ReactBricksApp>{children}</ReactBricksApp>
        </main>
      </body>
    </html>
  );
}
