import StoryblokProvider from "@/components/StoryblokProvider";
import "./globals.css";

export const metadata = {
  title: "Axen Property",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </StoryblokProvider>
  );
}
